"""
rag_assistant.py — RAG pipeline orchestrator for PKA-AI.

Wires retrieval → context building → prompt → LLM generation into
one injectable, testable class.

Pipeline:
    question
        ↓  retriever.retrieve()
    top-k chunks
        ↓  _build_context()
    context string
        ↓  prompt_builder.build()
    prompt string
        ↓  llm_client.generate()
    answer string

Dependencies are injected via __init__, so each component can be
swapped or mocked independently in tests.
"""

import logging

logger = logging.getLogger(__name__)


class RAGAssistant:
    """
    End-to-end RAG assistant.

    Args:
        retriever      — Any object with a .retrieve(question, k) method.
                         Expected to return a list of chunk dicts:
                         [{"text": str, "metadata": dict, ...}, ...]

        prompt_builder — Any object with a .build(context, question) method.
                         Expected to return a prompt string.

        llm_client     — Any object with a .generate(prompt) method.
                         Expected to return an answer string.
    """

    def __init__(self, retriever, prompt_builder, llm_client):
        self.retriever = retriever
        self.prompt_builder = prompt_builder
        self.llm_client = llm_client

    # ── Public API ────────────────────────────────────────────────────────────

    def ask(self, question: str, k: int = 5) -> str:
        """
        Run the full RAG pipeline for a single question.

        Args:
            question : Natural-language question from the user.
            k        : Number of chunks to retrieve (default 5).

        Returns:
            Answer string generated by the LLM.
        """
        # Step 1 — Retrieve relevant chunks
        logger.info(f"[RAGAssistant] Retrieving top-{k} chunks...")
        chunks = self.retriever.retrieve(question, k=k)

        logger.debug("QUESTION\n%s", question)
        logger.debug("CHUNKS\n%s", chunks)

        # Step 2 — Build context string
        context = self._build_context(chunks)

        # Step 3 — Build prompt
        logger.info("[RAGAssistant] Building prompt...")
        prompt = self.prompt_builder.build(context=context, question=question)

        logger.debug("PROMPT\n%s", prompt)

        # Step 4 — Generate answer
        logger.info("[RAGAssistant] Calling LLM...")
        answer = self.llm_client.generate(prompt)

        logger.debug("ANSWER\n%s", answer)

        return answer

    # ── Private helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _build_context(chunks: list) -> str:
        """
        Joins retrieved chunk texts into a single context string.

        Chunks are separated by a blank line so the LLM sees them as
        distinct passages rather than one continuous block of text.

        Args:
            chunks : List of chunk dicts, each with at least a "text" key.

        Returns:
            Multi-paragraph context string, or a fallback message if empty.
        """
        if not chunks:
            return "(No context retrieved.)"

        return "\n\n".join(
            chunk["text"].strip()
            for chunk in chunks
            if chunk.get("text")
        )